[package]
name = "goblin-governance"
version = "0.0.1"
authors = ["LuncGoblins"]
edition = "2021"
description = "Common goblin governance types"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
cosmwasm-std = { version = "1.1" }
schemars = "0.8.1"
serde = { version = "1.0.103", default-features = false, features = ["derive"] }
uint = "0.9"
cw-storage-plus = "0.16"
thiserror = "1"
cosmwasm-schema = "1.1"